### ISSUE TITLE
在React Native环境下使用会出现Navigator重置的现象

### ISSUE THREAD

**Issue by gdtdpt** [nanxiaobei/flooks#10]
你好，我非常喜欢你对redux理解和这个flooks库。
但是最近我想将flooks应用在React Native上，因为 我知道redux在React和React Native上使用的库是一样的，我想当然的认为flooks应该也差不多。
但是当我使用后发现当我在跳转到某个路由下使用`useModel`拿到action然后使用action修改state时发现我的navigator被重置到初始状态了，就是跳到了路由设置的默认页面。
之后我尝试使用redux写了个demo，发现redux dispatch action改变state时不会重置路由。
所以想请教一下对于这个问题有什么思路吗？如果对RN不感兴趣的话能否给点提示以便我对源码进行修改。谢谢

我测试的环境：
```json
"dependencies": {
    "flooks": "^1.2.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.1",
    "react-native-reanimated": "^1.4.0",
    "react-native-screens": "^2.0.0-alpha.13",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.6.0"
  },
```
系统：macOS Mojave
IDE: vs code
RN版本：react-native-cli: 2.0.1

**Comment by gdtdpt** [comment]
看到在已经关闭的issue中有写到1.2版本有onlyActions参数，试了一下，解决了我的问题。

**Comment by nanxiaobei** [comment]
好的~
