### ISSUE TITLE
在安卓 4.4 系统上，会出现 js 报错，定位到是 flooks 导致的，是不是需要做某些工作去 hack？

### ISSUE THREAD

**Issue by Eleven90** [nanxiaobei/flooks#19]

**Comment by nanxiaobei** [comment]
有具体报错信息吗

**Comment by Eleven90** [comment]
> 有具体报错信息吗

控制台提示没有 setPrototypeOf 方法，
我看了下打包的产物，似乎所有的新语法都没有做 polyfill 的转译，在 dist/flooks.esm.js、dist/flooks.cjs.js 产物里看，你这边用到的 Symbol/WeakMap/setPrototypeOf 等，产物里都没有编译的 polyfill 相关代码。

**Comment by nanxiaobei** [comment]
setPrototypeOf 是 ES5 的 API，理论上是不会去考虑其兼容性的，https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf

如果有特殊平台（比如旧版本 Android）的特殊情况，建议自行引入 polyfill 文件

**Comment by Eleven90** [comment]
在 dist/flooks.esm.js 里可以看到，WeakMap 等也没有相关的 polyfill 转码，你这边 rollup 的 babel 相关转码可能需要看一下。

**Comment by Eleven90** [comment]
> 在 dist/flooks.esm.js 里可以看到，WeakMap 等也没有相关的 polyfill 转码，你这边 rollup 的 babel 相关转码可能需要看一下。


![image](https://user-images.githubusercontent.com/20358391/89287159-053bfa80-d686-11ea-9188-2c8f077794ee.png)

建议分析一下产物，你那边 rollup 仅做了 let/const/箭头函数 等语法转译，其它 ES 的新 API 均没有做转码，大概看了下，目前兼容性应该 IE11 都覆盖不到。
