### ISSUE TITLE
未做 ES 新 API 转码

### ISSUE THREAD

**Issue by Eleven90** [nanxiaobei/flooks#20]
从 flooks/dist/ 下的编译产物看，仅做了 ES 新语法的翻译，对于 ES 的新 API（例如：WeakMap、keys、Symbol 等）没有转码。

![image](https://user-images.githubusercontent.com/20358391/89361957-34db1900-d6ff-11ea-977e-06142fe6d662.png)
![image](https://user-images.githubusercontent.com/20358391/89362002-51775100-d6ff-11ea-9185-b75ddfddda04.png)

**Comment by Eleven90** [comment]
上一个 issues 关闭地太快了，建议作者可以重视一下，放在生产上试用，很不幸只能下掉了。

**Comment by nanxiaobei** [comment]
https://github.com/dgraham/delegated-events/issues/18

**Comment by Eleven90** [comment]
> [dgraham/delegated-events#18](https://github.com/dgraham/delegated-events/issues/18)

你编译的产物肯定是要做转码的.............

**Comment by nanxiaobei** [comment]
polyfill 可自行引入，不会为了支持 Android 4.4 版本这种过旧的 WebView 而在库中专门引入 polyfill。

不会为了支持极小众的兼容情况，而使全部用户都引入本来用不到的 polyfill。

**Comment by Eleven90** [comment]
> polyfill 可自行引入，不会为了支持 Android 4.4 版本这种过旧的 WebView 而在库中专门引入 polyfill。
> 
> 不会为了支持极小众的兼容情况，而使全部用户都引入本来用不到的 polyfill。

好吧好吧，你赢了。
建议您比对一下其它开源库是否做转码
