### ISSUE TITLE
BugDemo

### ISSUE THREAD

**Issue by cceevv** [nanxiaobei/flooks#37]
看例子：
[![Edit flooks](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/flooks-forked-miplp?file=/src/BugDemo.jsx)

```jsx
import useModel from 'flooks';
import { useEffect } from 'react';

const store = ({ get, set }) => ({
  label: '6666666666',
  setLabel(str) {
    set({ label: str });
  },
});

const SubView = () => {
  const { setLabel } = useModel(store);

  useEffect(() => {
    console.log('change label to 77777777');
    setLabel('77777777');
  });

  return (
    <div>
      <h2>SubView</h2>
      Here change the label to 77777777.
    </div>
  );
};

const BugDemo = () => {
  const { label } = useModel(store);

  return (
    <div>
      <h2>BugDemo</h2>
      label: {label}
      <br />
      <br />
      <br />
      <SubView />
    </div>
  );
};

export default BugDemo;
```

父子组件引用同一个store，子组件初始化时更新store数据，更新的数据不会同步到父组件。

因为子组件更新数据时，父组件还没执行到这一行： [`modelSubs.push(updater);`](https://github.com/nanxiaobei/flooks/blob/main/src/index.ts#L125) 导致父组件的 updater 没被执行到。

[useModel](https://github.com/nanxiaobei/flooks/blob/main/src/index.ts#L21) 里的那个 [useEffect](https://github.com/nanxiaobei/flooks/blob/main/src/index.ts#L104) 是在子组件的 useEffect 之后执行的，也就是说 useModel 在初始化过程中（由子组件）变更的数据不会响应到当前 useModel 的组件，因为 updater 还没初始化完毕。

**Comment by nanxiaobei** [comment]
`4.1.0` 已修复。
