### ISSUE TITLE
后续有添加 Context 支持计划吗？

### ISSUE THREAD

**Issue by MinJieLiu** [nanxiaobei/flooks#40]
例如：

```js
import createContext from 'zustand/context';

const { Provider, useStore, useStoreApi } = createContext();
```

**Comment by nanxiaobei** [comment]
没太理解这个 Context 方案是用来解决什么情况~

**Comment by MinJieLiu** [comment]
没有 Context 就是单例，这样应用不能保证数据的隔离性。

扯远一点，现在不是有很多系统有多标签页嘛，类似 Vue 的 keep-alive，目前社区也有 react 实现。如果不隔离，两个同一页面的路由之间的数据就是串的。

**Comment by nanxiaobei** [comment]
多调用几次 `create()` 创建不同的 `store` 可以解决吗？

**Comment by nanxiaobei** [comment]
其实这个设计的本意，不是总共一个 store，而是根据实际业务，一个 "模块" 一个 "store"，来进行数据隔离。
