### ISSUE TITLE
如何在条件语句中或者事件回调函数中访问state

### ISSUE THREAD

**Issue by bacy** [nanxiaobei/flooks#43]
只想拿a的数据，一定要在组件顶层先const { a } = useXXX();吗？会不会导致这个组件无效渲染

**Comment by nanxiaobei** [comment]
1. 条件语句中访问 a，而 a 又不作为 state 来看待，依我的经验，这么写应该是会有 bug 的。
2. 回调函数中访问 a，可以把这个回调函数写入 store。
