### ISSUE TITLE
性能

### ISSUE THREAD

**Issue by Opelar** [nanxiaobei/flooks#5]
Uncaught Invariant Violation: Too many re-renders. React limits the number of renders to prevent an infinite loop.

**Comment by Opelar** [comment]
![image](https://user-images.githubusercontent.com/16917000/64529885-7f60e380-d33e-11e9-85e3-7dd59c266466.png)

在state树比较大一点，setter多一点的情况下会频繁的重复渲染，然后报上面的错

**Comment by nanxiaobei** [comment]
你好，可以提供一个复现的 demo 吗？
我试了下，渲染了 10,000 个元素，同时更新 state，也没有出现这个错误提示。

**Comment by Opelar** [comment]
是自己代码问题
