### ISSUE TITLE
在事件中使用渲染时没有调用的值就会报错

### ISSUE THREAD

**Issue by gitivon** [nanxiaobei/flooks#50]
![image](https://github.com/nanxiaobei/flooks/assets/3938359/44e8ae8d-07d2-48b0-8fa2-f8bb7cefd7b1)
如图，虽然可以通过先解构赋值然后再调用。但我想更灵活一些的话，大佬有什么办法吗？

**Comment by nanxiaobei** [comment]
请更新至 `6.3.0`，已支持此种写法~
