### ISSUE TITLE
store里的方法返回值都是promise

### ISSUE THREAD

**Issue by huahaichuan** [nanxiaobei/flooks#52]
store里的方法返回值都是promise，这个有什么办法处理吗？

**Comment by huahaichuan** [comment]
> 不是 promise 吧。遇到了什么问题？想要实现什么效果？可以提供一个可复现最小 demo

例如：hasBtnAuth: (code: AuthCode) => {
    const { authIds } = store();
    return authIds.includes(code);
  }
返回的是一个promise，当时项目比较急，选择的降到版本5解决的。

**Comment by nanxiaobei** [comment]
无法复现，可提供一个复现 demo

**Comment by nanxiaobei** [comment]
`6.4.0` 已更新
