### ISSUE TITLE
能否改造在 Taro 中使用

### ISSUE THREAD

**Issue by gendseo** [nanxiaobei/flooks#6]
能否改造在 Taro 中使用

**Comment by nanxiaobei** [comment]
flooks 中用到了 React Hooks 的 `useState` 和 `useEffect`，理论上，把代码中的 `react` 改为 `@tarojs/taro` 就可以了~

https://nervjs.github.io/taro/docs/hooks.html

**Comment by gendseo** [comment]
是的，我现在正尝试改造项目依赖，希望能封装成一个taro使用的库。
