### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by xichengh** [nanxiaobei/flooks#8]
建议将actions和state的使用分开，或者标记setter,  用一个useModel的时候会出现一个只使用了action的组件，在setState的时候也就是setters遍历运行时会重新渲染

**Comment by nanxiaobei** [comment]
你好，可以提供一个 demo 说明一下期望情况吗？

**Comment by xichengh** [comment]
[https://codesandbox.io/s/flooks-2dsxs?fontsize=14](url)
## 例子中组件a只使用了setName，希望在name变化的时候不重新渲染

**Comment by nanxiaobei** [comment]
你好，感谢反馈。

增加了 `useModel` 的第二个参数 [`onlyActions`](https://github.com/nanxiaobei/flooks#2-usemodel)，传入 `true` 以阻止组件重新渲染。

可升级 `1.2` 版本使用。
